[files]
extend-exclude = [
  "modules/eric/desktop/sketchybar/helpers/app_icons.lua",
  "secrets/*",
]

[default]
extend-ignore-re = ["rgba\\([^)]*\\)"]

[default.extend-words]
Pn = "Pn"
Ot = "Ot"
edn = "edn"
Ony = "Ony"
