hl.config({ autogenerated = false })

-- nvidia env (3070, Ampere), per Hyprland Nvidia docs
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
-- Belt-and-suspenders: kill HW cursor at the wlroots layer too (still needed on NVIDIA)
hl.env("WLR_NO_HARDWARE_CURSORS", "1")

-- Disable hardware cursors + force CPU buffer (NVIDIA phantom-cursor fix)
hl.config({ cursor = { no_hardware_cursors = true, use_cpu_buffer = true } })

-- Cursor theme (XCursor only, no Catppuccin hyprcursor theme exists)
hl.env("XCURSOR_THEME", "catppuccin-mocha-dark-cursors")
hl.env("XCURSOR_SIZE", "24")

-- Remap CapsLock -> Escape; require click to focus windows
hl.config({ input = { kb_options = "caps:escape", follow_mouse = 0 } })

-- Drag window borders to resize (no modifier needed)
hl.config({ general = { resize_on_border = true } })

-- Suppress Hyprland's built-in default wallpaper/logo on login
hl.config({ misc = { force_default_wallpaper = 0, disable_hyprland_logo = true } })

-- Window opacity + blur
hl.config({
    decoration = {
        active_opacity = 0.95,
        inactive_opacity = 0.85,
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = true,
        },
    },
})

-- moonlight/sunshine target: a virtual monitor parked far off to the side so
-- the physical display never shows the streamed session
hl.monitor({
    output = "HEADLESS-1",
    mode = "1920x1080@60",
    position = "9999x0",
    scale = 1,
})
hl.workspace_rule({ workspace = "11", monitor = "HEADLESS-1", persistent = true })

-- Autostart daemons inside the UWSM systemd scope
hl.on("hyprland.start", function()
    -- Re-import Hyprland-set env (HYPRLAND_INSTANCE_SIGNATURE, etc.) into the
    -- systemd user manager so uwsm-app scopes and `hyprctl` from terminals work.
    hl.dispatch(
        hl.dsp.exec_cmd(
            "systemctl --user import-environment HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
        )
    )
    hl.dispatch(
        hl.dsp.exec_cmd(
            "dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
        )
    )

    hl.dispatch(hl.dsp.exec_cmd("uwsm app -- swaync"))
    hl.dispatch(hl.dsp.exec_cmd("systemctl --user start hyprpolkitagent"))
    hl.dispatch(hl.dsp.exec_cmd("uwsm app -- hypridle"))
    hl.dispatch(hl.dsp.exec_cmd("uwsm app -- hyprpaper"))

    -- create the headless output before sunshine reads output_name
    hl.dispatch(hl.dsp.exec_cmd("sh -c 'hyprctl output create headless; systemctl --user start sunshine'"))
end)

local mod = "SUPER"
local term = "wezterm"
local menu = "fuzzel"
local files = "nautilus"
local web = "firefox"

-- apps
hl.bind(mod .. " + Return", hl.dsp.exec_cmd(term))
hl.bind(mod .. " + D", hl.dsp.exec_cmd(menu))
hl.bind(mod .. " + E", hl.dsp.exec_cmd(files))
hl.bind(mod .. " + B", hl.dsp.exec_cmd(web))
hl.bind(mod .. " + L", hl.dsp.exec_cmd("hyprlock"))

-- window
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mod .. " + P", hl.dsp.window.pseudo()) -- inferred API
hl.bind(mod .. " + J", hl.dsp.layout("togglesplit")) -- dwindle only
hl.bind(mod .. " + SHIFT + Q", hl.dsp.exec_cmd("hyprshutdown"))
hl.bind(mod .. " + SHIFT + E", hl.dsp.exit())

-- focus (arrows + hjkl)
for k, dir in pairs({
    left = "l",
    right = "r",
    up = "u",
    down = "d",
    h = "l",
    l = "r",
    k = "u",
    j = "d",
}) do
    hl.bind(mod .. " + " .. k, hl.dsp.focus({ direction = dir }))
end

-- move window
for k, dir in pairs({ left = "l", right = "r", up = "u", down = "d" }) do
    hl.bind(mod .. " + SHIFT + " .. k, hl.dsp.window.move({ direction = dir })) -- inferred API
end

-- resize (repeats while held)
local rep = { repeating = true }
for k, delta in pairs({ left = { -40, 0 }, right = { 40, 0 }, up = { 0, -40 }, down = { 0, 40 } }) do
    hl.bind(mod .. " + ALT + " .. k, hl.dsp.window.resize({ x = delta[1], y = delta[2] }), rep)
end

-- workspaces
for i = 1, 9 do
    hl.bind(mod .. " + " .. i, hl.dsp.focus({ workspace = i }))
    hl.bind(mod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mod .. " + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind(mod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mod .. " + CTRL + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + CTRL + left", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + Tab", hl.dsp.focus({ workspace = "previous" }))

hl.bind(mod .. " + S", hl.dsp.workspace.toggle_special("scratch"))
hl.bind(mod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:scratch" }))

-- mouse
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- screenshots (grimblast)
hl.bind("Print", hl.dsp.exec_cmd("grimblast --notify --cursor copy output"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grimblast --notify --freeze copy area"))
hl.bind(mod .. " + Print", hl.dsp.exec_cmd("grimblast --notify copy screen"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("grimblast --notify copy active"))

-- media / brightness
local lr = { locked = true, repeating = true }
local lo = { locked = true }
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), lr)
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), lr)
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute   @DEFAULT_AUDIO_SINK@   toggle"), lo)
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute   @DEFAULT_AUDIO_SOURCE@ toggle"), lo)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), lr)
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), lr)
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), lo)
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), lo)
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), lo)
