{
  inputs,
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    ./hardware/x86_64-hetzner.nix
    ../modules/base.nix
    # ../modules/desktop-gnome.nix
    ../modules/users-eric.nix
    ../modules/ssh.nix
    ../modules/rust.nix
    ../modules/sops.nix
  ];

  # extra modules just in case
  boot = {
    loader.grub.device = "/dev/sda";
    initrd = {
      kernelModules = [ "nvme" ];
      availableKernelModules = [
        "ata_piix"
        "uhci_hcd"
        "xen_blkfront"
        "vmw_pvscsi"
      ];
    };
  };

  # root ssh key, no longer used
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID8ZSvpHzLHQLTK+LkDV0TNkhJRHRHBPUbcrgEy3c8sA ericshen118@gmail.com"
  ];

  # generated by nix-infect
  networking = {
    hostName = "squid";
    domain = "";
    nameservers = [
      "8.8.8.8"
    ];
    defaultGateway = "172.31.1.1";
    defaultGateway6 = {
      address = "fe80::1";
      interface = "eth0";
    };
    dhcpcd.enable = false;
    usePredictableInterfaceNames = lib.mkForce false;
    interfaces = {
      eth0 = {
        ipv4.addresses = [
          {
            address = "91.107.217.214";
            prefixLength = 32;
          }
        ];
        ipv6.addresses = [
          {
            address = "2a01:4f8:c17:ef11::1";
            prefixLength = 64;
          }
          {
            address = "fe80::9400:4ff:fe5a:c38b";
            prefixLength = 64;
          }
        ];
        ipv4.routes = [
          {
            address = "172.31.1.1";
            prefixLength = 32;
          }
        ];
        ipv6.routes = [
          {
            address = "fe80::1";
            prefixLength = 128;
          }
        ];
      };

    };
  };
  services.udev.extraRules = ''ATTR{address}=="96:00:04:5a:c3:8b", NAME="eth0"'';

}
