"$schema" = "https://starship.rs/config-schema.json"

### MAIN SHELL
# directory username[@hostname] git direnv duration
# os ▶

format = """
[┌┤](surface1)\
$directory\
[├┤](surface1)$hostname\
$git_branch\
$git_commit\
$git_state\
$git_status\
$direnv\
$cmd_duration\
$line_break\
[└┤](surface1)\
$os\
$character"""

scan_timeout = 30
command_timeout = 200
add_newline = true

follow_symlinks = false

[directory.substitutions]
".config" = " "
"nixos-config" = " "
"Desktop" = " "
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"/dev/" = "/ /"

[shell]
disabled = true
bash_indicator = "bash"
fish_indicator = "fish"
zsh_indicator = "zsh"
powershell_indicator = "pwsh"
cmd_indicator = "cmd"

[character]
success_symbol = "[▶](bold teal)"
error_symbol = "[▶](bold red)"
vimcmd_symbol = "[▷](bold teal)"

[os]
disabled = false
format = "[$symbol]($style)"
style = "green"

[os.symbols]
Macos = " "
Linux = " "
Windows = " "
NixOS = " "
Ubuntu = " "
Arch = " "
Debian = " "
Fedora = " "

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "teal"
read_only = " "
use_os_path_sep = false
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"

[username]
show_always = true
format = "[$user]($style)"
style_user = "yellow"
style_root = "red"

[hostname]
ssh_only = true
format = "[$hostname]($style)"
style = "yellow"
trim_at = "."

[sudo]
disabled = true
format = "[$symbol]($style)"
style = "red"
symbol = " "

[shlvl]
disabled = true
format = "[├┤](surface1)[$symbol]($style)"
threshold = 2
symbol = "*"
repeat = true

[direnv]
disabled = false
format = "[├┤](surface1)[$symbol$allowed$loaded]($style)"
symbol = " "
allowed_msg = ""
not_allowed_msg = "?"
denied_msg = "×"
loaded_msg = "✓"
unloaded_msg = "-"

[git_metrics]
disabled = true
format = "[├┤](surface1)[+$added](green)/[-$deleted](red)"
added_style = "green"
deleted_style = "red"

[git_branch]
symbol = " "
format = "[├┤](surface1)[$symbol$branch]($style)"
style = "pink"

[git_commit]
only_detached = true
tag_disabled = false
format = " [$hash$tag]($style)"
style = "pink"

[git_state]
format = " [$state( $progress_current/$progress_total)]($style)"
style = "pink"

[git_status]
format = "( [$all_status$ahead_behind]($style))"
ahead = "↑"
behind = "↓"
conflicted = "!"
deleted = "×"
diverged = "↕"
modified = "~"
renamed = "»"
untracked = "+"
style = "pink"

[fill]
symbol = "─"
style = "surface1"

[time]
disabled = true
format = "[├┤](surface1)[ $time]($style)"

[cmd_duration]
format = "[├┤](surface1)[󰚭 $duration]($style)"
min_time = 0
show_milliseconds = true
style = "yellow"
