approvals_reviewer = "user"
approval_policy = "on-request"
model = "gpt-5.6-sol"
model_reasoning_effort = "high"
notify = [
  "/Users/eric/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient",
  "turn-ended",
]
personality = "pragmatic"
project_doc_fallback_filenames = ["CLAUDE.md"]
sandbox_mode = "workspace-write"
service_tier = "default"

[sandbox_workspace_write]
network_access = true

[desktop]
conversationDetailMode = "STEPS_PROSE"
dock-icon-preference = "codex-system"
followUpQueueMode = "queue"
show-context-window-usage = false
avatar-overlay-pet-visible = false
hotkey-window-projectless-default-enabled = true

[desktop.appearanceDarkChromeTheme]
accent = "#339cff"
contrast = 60
ink = "#ffffff"
opaqueWindows = false
surface = "#181818"

[desktop.appearanceDarkChromeTheme.fonts]
code = "Hack Nerd Font"

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#40c977"
diffRemoved = "#fa423e"
skill = "#ad7bf9"

[features]
hooks = true
js_repl = false
memories = true
mentions_v2 = true
multi_agent = true
steer = true
terminal_resize_reflow = true

[marketplaces.openai-bundled]
source_type = "local"
source = "/Users/eric/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/eric/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[mcp_servers.computer-use]
args = ["mcp"]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
cwd = "."
enabled = false

[mcp_servers.cornell-confluence]
command = "/etc/profiles/per-user/eric/bin/cornell-confluence-mcp"

[mcp_servers.context7]
command = "/etc/profiles/per-user/eric/bin/context7-mcp"

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/eric/.codex:/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
CODEX_HOME = "/Users/eric/.codex"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab,mcpapps"
BROWSER_USE_TINYSKY_ENABLED = "1"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = ""
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.928.20755"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"/Users/eric/.codex/plugins/cache/openai-bundled/browser/26.928.20755/scripts/browser-service.mjs","sky":"@oai/sky/service"}'
SKY_CUA_SERVICE_PATH = "/Users/eric/.codex/computer-use/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex-cli/CodexCLI.app/Contents/MacOS/codex"

[mcp_servers.railway]
args = ["mcp"]
command = "railway"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.4"
"gpt-5.4" = "gpt-5.5"

[plugins."browser@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = false

[plugins."spreadsheets@openai-primary-runtime"]
enabled = false

[plugins."template-creator@openai-primary-runtime"]
enabled = false

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[plugins."code-review@openai-bundled"]
enabled = true

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-analytics-dashboard"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-business-review"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-design-report"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-experiment-analysis"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-financial-budget"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-investment-committee-memo"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-legal-memorandum"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-market-trends-report"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-minimal-letterhead"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-operating-calendar"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-operating-review"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-project-kickoff"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-project-tracker"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-sales-pipeline"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-simple-dark-mode"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-simple-light-mode"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-strategy-memorandum"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-system-design"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-team-alignment"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/openai-templates/0.1.1/skills/artifact-template-three-statement-forecast"
enabled = false

[[skills.config]]
path = "/Users/eric/.codex/plugins/cache/openai-curated-remote/plugin-management/0.1.0/skills/plugin-management"
enabled = false

[projects."/Users/eric"]
trust_level = "untrusted"

[projects."/Users/eric/.config"]
trust_level = "trusted"

[projects."/Users/eric/.config/fastfetch"]
trust_level = "trusted"

[projects."/Users/eric/.config/sketchybar"]
trust_level = "trusted"

[projects."/Users/eric/.vscode"]
trust_level = "trusted"

[projects."/Users/eric/Desktop/cornell/math3360"]
trust_level = "trusted"

[projects."/Users/eric/Documents/Codex/2026-07-10/hi"]
trust_level = "trusted"

[projects."/Users/eric/Documents/Codex/2026-07-10/sites-plugin-sites-openai-bundled-create"]
trust_level = "trusted"

[projects."/Users/eric/Library/Application Support/Firefox/Profiles"]
trust_level = "trusted"

[projects."/Users/eric/dev"]
trust_level = "trusted"

[projects."/Users/eric/dev/DPP"]
trust_level = "trusted"

[projects."/Users/eric/dev/GokuRakuJoudo"]
trust_level = "trusted"

[projects."/Users/eric/dev/RaceEngineerDashboard"]
trust_level = "trusted"

[projects."/Users/eric/dev/SketchyBar"]
trust_level = "trusted"

[projects."/Users/eric/dev/agent-container"]
trust_level = "trusted"

[projects."/Users/eric/dev/agentbox-claude-code"]
trust_level = "trusted"

[projects."/Users/eric/dev/atuin"]
trust_level = "trusted"

[projects."/Users/eric/dev/cornell/catc/Primary_Pipeline"]
trust_level = "trusted"

[projects."/Users/eric/dev/cornell/cev/RaceEngineerDashboard"]
trust_level = "trusted"

[projects."/Users/eric/dev/cornell/cev/tailscale-ros-telemetry"]
trust_level = "trusted"

[projects."/Users/eric/dev/cornell/cev/uc26_sensor_reader"]
trust_level = "trusted"

[projects."/Users/eric/dev/cornell/cev/uc26_sensor_reader/can/RP2040_MCP251863_Driver"]
trust_level = "trusted"

[projects."/Users/eric/dev/cornell/cs3110"]
trust_level = "trusted"

[projects."/Users/eric/dev/cornell/cs3110-proj/a4"]
trust_level = "trusted"

[projects."/Users/eric/dev/cornell/cs3110project"]
trust_level = "trusted"

[projects."/Users/eric/dev/cppssh"]
trust_level = "trusted"

[projects."/Users/eric/dev/defaultb"]
trust_level = "trusted"

[projects."/Users/eric/dev/eirkbot-cpp"]
trust_level = "trusted"

[projects."/Users/eric/dev/eriz-links"]
trust_level = "trusted"

[projects."/Users/eric/dev/knot"]
trust_level = "trusted"

[projects."/Users/eric/dev/metal-lsp"]
trust_level = "trusted"

[projects."/Users/eric/dev/mfl"]
trust_level = "trusted"

[projects."/Users/eric/dev/mnist-mlp"]
trust_level = "trusted"

[projects."/Users/eric/dev/nixpkgs"]
trust_level = "trusted"

[projects."/Users/eric/dev/ocaml-raytracer"]
trust_level = "trusted"

[projects."/Users/eric/dev/ocaml-voxel"]
trust_level = "trusted"

[projects."/Users/eric/dev/other/raycast-extensions"]
trust_level = "trusted"

[projects."/Users/eric/dev/particle"]
trust_level = "trusted"

[projects."/Users/eric/dev/resume"]
trust_level = "trusted"

[projects."/Users/eric/dev/rmouse"]
trust_level = "trusted"

[projects."/Users/eric/dev/sidebery"]
trust_level = "trusted"

[projects."/Users/eric/dev/smhkd"]
trust_level = "trusted"

[projects."/Users/eric/dev/starship"]
trust_level = "trusted"

[projects."/Users/eric/dev/state-machine"]
trust_level = "trusted"

[projects."/Users/eric/dev/website"]
trust_level = "trusted"

[projects."/Users/eric/dev/wezterm"]
trust_level = "trusted"

[projects."/Users/eric/dev/workers"]
trust_level = "trusted"

[projects."/Users/eric/dev/yabai"]
trust_level = "trusted"

[projects."/Users/eric/nixos-config"]
trust_level = "untrusted"

[projects."/opt/homebrew/Library/Taps/erics118/homebrew-tap"]
trust_level = "trusted"

[projects."/Users/eric/dev/alcove"]
trust_level = "trusted"

[projects."/Users/eric/Documents/Codex/2026-09-22/hi"]
trust_level = "trusted"

[projects."/Users/eric/dev/cornell/club/cev/urban-concept"]
trust_level = "trusted"

[shell_environment_policy.set]
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "028a14b6eaa6d98dac2aae00764345ab9f244801ed8493d42b9af3be5575006e,f204d340535055781952b10ed396de20b842f00a19e430852f7e121ad1ce91f6"

[tui]
status_line = [
  "model-with-reasoning",
  "current-dir",
  "git-branch",
  "context-used",
  "five-hour-limit",
  "weekly-limit",
]
status_line_use_colors = true
terminal_title = ["activity", "project-name", "current-dir"]
screen_reader_detection_done = true

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4
gpt-6-astra = 4
"gpt-6.1-sol" = 1

[hooks.state."/Users/eric/.codex/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:9f5efe0b15abbd66b247a093b660a0985f97f30283e7d1d82324807ab4cd4b7e"

[hooks.state."/Users/eric/.codex/hooks.json:pre_tool_use:0:1"]
trusted_hash = "sha256:5fa229b1d59fe6cedc2a1b7527ef842d29a2fd4066bfa0e98bf92da1d16e8e28"

[hooks.state."/Users/eric/.codex/hooks.json:pre_tool_use:0:2"]
trusted_hash = "sha256:61df246c12fd6a6f686b9ad5fe9896d0db32854cc2b51b8c2752d3ad18ba476c"

[hooks.state."/Users/eric/.codex/hooks.json:pre_tool_use:0:3"]
trusted_hash = "sha256:4dd0f2c9c532a539f0119085557b20f0d434dea73f6f1312df14ca038574e6ff"

[hooks.state."/Users/eric/.codex/hooks.json:pre_tool_use:0:4"]
trusted_hash = "sha256:280855a5fd48577f2bf75615361aa5915280a3ea8aa2573ea1e32be01aeb7a5a"

[hooks.state."/Users/eric/.codex/hooks.json:pre_tool_use:0:5"]
trusted_hash = "sha256:b440d0214be680d6c1b4a4ed257939aeda2fcd78497d6e9857ec510ad74b54ea"

[hooks.state."/Users/eric/.codex/hooks.json:pre_tool_use:0:6"]
trusted_hash = "sha256:118987d2419aaf15d66bf228cd186ca66f6aba992b956996119465f25a96dc21"

[hooks.state."/Users/eric/.codex/hooks.json:pre_tool_use:0:7"]
trusted_hash = "sha256:0dc608aac4f81cc0a450eaf587585d68ec200c9e8121fff12953360466806362"
