{
  config,
  lib,
  mkHome,
  ...
}:
let
  m = config.flake.modules;
in
{
  configurations.nixos.squid.module = {
    imports = [
      m.nixos.base
      m.nixos.ssh-server
      m.nixos.sops
      m.nixos.docker
      m.nixos.tailscale
      m.nixos.cachix-push
      ./_hardware/x86_64-hetzner.nix
    ];
    nixpkgs.hostPlatform = "x86_64-linux";

    # public-facing host: override the trusted-LAN defaults from base-nixos.
    # only ssh (22) is reachable; reach everything else over tailscale.
    services.openssh.settings.PasswordAuthentication = lib.mkForce false;

    # extra modules just in case
    boot = {
      loader.grub.device = "/dev/sda";
      initrd = {
        kernelModules = [ "nvme" ];
        availableKernelModules = [
          "ata_piix"
          "uhci_hcd"
          "xen_blkfront"
          "vmw_pvscsi"
        ];
      };
    };

    # generated by nix-infect
    networking = {
      hostName = "squid";
      domain = "";
      nameservers = [ "8.8.8.8" ];
      firewall = {
        enable = lib.mkForce true;
        allowedTCPPorts = [ 22 ];
      };
      defaultGateway = {
        address = "172.31.1.1";
        interface = "eth0";
      };
      defaultGateway6 = {
        address = "fe80::1";
        interface = "eth0";
      };
      dhcpcd.enable = false;
      usePredictableInterfaceNames = lib.mkForce false;
      interfaces = {
        eth0 = {
          ipv4.addresses = [
            {
              address = "91.107.217.214";
              prefixLength = 32;
            }
          ];
          ipv6.addresses = [
            {
              address = "2a01:4f8:c17:ef11::1";
              prefixLength = 64;
            }
            {
              address = "fe80::9400:4ff:fe5a:c38b";
              prefixLength = 64;
            }
          ];
          ipv4.routes = [
            {
              address = "172.31.1.1";
              prefixLength = 32;
            }
          ];
          ipv6.routes = [
            {
              address = "fe80::1";
              prefixLength = 128;
            }
          ];
        };

      };
    };
    services.udev.extraRules = ''ATTR{address}=="96:00:04:5a:c3:8b", NAME="eth0"'';
  };

  configurations.homeManager."eric@squid" = mkHome { system = "x86_64-linux"; };
}
